services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FIREBASE_API_KEY
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        - NEXT_PUBLIC_FIREBASE_APP_ID
        - FIREBASE_PROJECT_ID
        - FIREBASE_CLIENT_EMAIL
        - FIREBASE_PRIVATE_KEY
    expose:
      - "3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.j2j.rule=Host(`j2j.pxndey.com`)"
      - "traefik.http.routers.j2j.entrypoints=web"
      - "traefik.http.services.j2j.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - jobless
      - proxy

networks:
  jobless:
    driver: bridge
  proxy:
    external: true
