services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.j2j.rule=Host(`j2j.pxndey.com`)"
      - "traefik.http.routers.j2j.entrypoints=web"
      - "traefik.http.services.j2j.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - jobless
      - proxy

networks:
  jobless:
    driver: bridge
  proxy:
    external: true
